.. mchoice:: KD.2.2.D
   :author: Kuri DiFede
   :difficulty: 4
   :basecourse: csawesome
   :topic: Unit2-Using-Objects/Exercises
   :from_source: F
   :answer_a: You must always use the keyword new when creating a new object
   :answer_b: Constructors always have the same name as the class
   :answer_c: A class can have more than one constructor
   :answer_d: Different objects of the same type use the same constructor
   :answer_e: All of the above are true.
   :correct: e
   :feedback_a: new is always used with a constructor
   :feedback_b: Constructors always have the same name as the class
   :feedback_c: Classes can have different constructors with different parameter lists
   :feedback_d: Constructors are written in the class, so two objects of the same type can call the same constructor
   :feedback_e: Correct! All are true.

   Which of the following statements about constructors is false?